version : "3.8"

services:
  puzzle-showdown:
    image: puzzle_showdown:latest
    ports:
      - '8080:8080'
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
  puzzle-showdown-frontend:
    image: puzzle_showdown_frontend:latest
    depends_on:
      - puzzle-showdown
    ports:
      - '80:80'