version : "3.8"

services:
  puzzle-showdown:
    image: puzzle-showdown:latest
    build:
      context: .
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      DB_URL: ${DATABASE_URL}
      DB_USERNAME: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: puzzle